branch-defaults:
  master:
    environment: Augmentoreact-env
    group_suffix: null
environment-defaults:
  Augmentoreact-env:
    branch: null
    repository: null
global:
  application_name: augmentoreact
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
