export const types={
    GET_POSTS:'getPosts',
    GET_RESULT:'getresult',


    GET_ADDITION:'GET_ADDITION',
    GET_SUBSTRACTION:'GET_SUBSTRACTION',
    GET_MULTIPLICATION:'GET_MULTIPLICATION',
    GET_DIVISION:'GET_DIVISION',


    GET_SIMPLEINTEREST:'GET_SIMPLEINTEREST',

    GET_WHEATHER:'GET_WHEATHER'
}